"""
Portfolio Manager – single source of truth for equity, positions, PnL and accounting.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from decimal import Decimal
from typing import Dict, List, Optional, Callable, Any

from core.types import (
    Fill,
    Order,
    Position as CorePosition,
    PortfolioSnapshot,
    Side,
    PositionSide,
    Event,
    EventType,
)
from portfolio.position import ManagedPosition

logger = logging.getLogger(__name__)


class PortfolioManager:
    """
    Tracks every position, calculates accurate realized/unrealized PnL,
    fees, funding payments, and exposes a clean snapshot for Risk + Dashboard.
    """

    def __init__(
        self,
        starting_equity: Decimal = Decimal("10000"),
        currency: str = "USDC",
    ):
        self.currency = currency
        self.starting_equity = starting_equity
        self.cash = starting_equity          # free cash / available balance
        self.positions: Dict[str, ManagedPosition] = {}
        self.closed_trades: List[ManagedPosition] = []

        self.realized_pnl_total = Decimal("0")
        self.fees_total = Decimal("0")
        self.funding_total = Decimal("0")

        self._event_callbacks: List[Callable[[Event], None]] = []
        self._equity_curve: List[Dict[str, Any]] = []
        self._record_equity()

    def on_event(self, callback: Callable[[Event], None]) -> None:
        self._event_callbacks.append(callback)

    def _emit(self, event_type: EventType, payload: Any) -> None:
        event = Event(type=event_type, payload=payload, source="portfolio")
        for cb in self._event_callbacks:
            try:
                cb(event)
            except Exception as e:
                logger.exception("Portfolio event callback error: %s", e)

    # ──────────────────────────────────────────────
    # Core accounting
    # ──────────────────────────────────────────────

    def apply_fill(self, fill: Fill, strategy_id: str = "") -> Decimal:
        """
        Apply a fill to the portfolio.
        Returns realized PnL generated by this fill.
        """
        symbol = fill.symbol
        pos = self.positions.get(symbol)

        if pos is None:
            pos = ManagedPosition(symbol=symbol, strategy_id=strategy_id)
            self.positions[symbol] = pos

        realized = pos.apply_fill(fill)

        # Cash impact
        notional = fill.quantity * fill.price
        if fill.side == Side.BUY:
            self.cash -= notional + fill.fee
        else:
            self.cash += notional - fill.fee

        self.realized_pnl_total += realized
        self.fees_total += fill.fee

        if not pos.is_open:
            # Position fully closed → move to history
            self.closed_trades.append(pos)
            del self.positions[symbol]
            self._emit(EventType.POSITION_UPDATE, pos)

        self._record_equity()
        self._emit(EventType.FILL, fill)
        return realized

    def update_marks(self, marks: Dict[str, Decimal]) -> None:
        """Update mark prices for all open positions (usually from ticker stream)."""
        for symbol, mark in marks.items():
            pos = self.positions.get(symbol)
            if pos and pos.is_open:
                pos.update_mark(mark)
        self._record_equity()

    def apply_funding(self, symbol: str, payment: Decimal) -> None:
        """
        Apply funding payment (positive = received, negative = paid).
        """
        pos = self.positions.get(symbol)
        if pos and pos.is_open:
            pos.apply_funding(payment)
            self.cash += payment          # funding is settled in cash
            self.funding_total += payment
            self._record_equity()
            logger.info("Funding %s on %s: %s", "received" if payment > 0 else "paid", symbol, payment)

    # ──────────────────────────────────────────────
    # Queries
    # ──────────────────────────────────────────────

    @property
    def equity(self) -> Decimal:
        unrealized = sum((p.unrealized_pnl for p in self.positions.values()), Decimal("0"))
        return self.cash + unrealized

    @property
    def used_margin(self) -> Decimal:
        # Simplified: for cross margin we use notional / leverage
        return sum((p.notional / max(p.leverage, Decimal("1")) for p in self.positions.values()), Decimal("0"))

    @property
    def available_balance(self) -> Decimal:
        return max(self.cash - self.used_margin, Decimal("0"))

    @property
    def unrealized_pnl(self) -> Decimal:
        return sum((p.unrealized_pnl for p in self.positions.values()), Decimal("0"))

    def get_position(self, symbol: str) -> Optional[ManagedPosition]:
        return self.positions.get(symbol)

    def get_open_positions(self) -> List[ManagedPosition]:
        return [p for p in self.positions.values() if p.is_open]

    def get_snapshot(self) -> PortfolioSnapshot:
        from core.types import Position as CorePos
        core_positions = []
        for p in self.get_open_positions():
            core_positions.append(
                CorePos(
                    symbol=p.symbol,
                    side=p.side,
                    quantity=abs(p.quantity),
                    entry_price=p.entry_price,
                    mark_price=p.mark_price,
                    unrealized_pnl=p.unrealized_pnl,
                    realized_pnl=p.realized_pnl,
                    leverage=p.leverage,
                    strategy_id=p.strategy_id,
                    opened_at=p.opened_at or datetime.now(timezone.utc),
                    updated_at=p.updated_at,
                )
            )

        return PortfolioSnapshot(
            timestamp=datetime.now(timezone.utc),
            equity=self.equity,
            available_balance=self.available_balance,
            used_margin=self.used_margin,
            unrealized_pnl=self.unrealized_pnl,
            realized_pnl_today=self.realized_pnl_total,  # simplified; real daily tracking in Risk
            open_positions=core_positions,
            open_orders=[],  # filled by engine
            daily_pnl=self.realized_pnl_total + self.unrealized_pnl,
            weekly_pnl=self.realized_pnl_total + self.unrealized_pnl,
            max_drawdown_pct=Decimal("0"),  # calculated by RiskManager
            risk_utilization_pct=(self.used_margin / max(self.equity, Decimal("1"))) * 100,
        )

    def get_equity_curve(self, limit: int = 1000) -> List[Dict[str, Any]]:
        return self._equity_curve[-limit:]

    def get_trade_journal(self, limit: int = 100) -> List[Dict[str, Any]]:
        journal = []
        for p in reversed(self.closed_trades[-limit:]):
            journal.append({
                "id": p.id,
                "symbol": p.symbol,
                "side": p.side.value,
                "quantity": float(abs(p.quantity)),
                "entry_price": float(p.entry_price),
                "exit_price": float(p.mark_price),
                "realized_pnl": float(p.realized_pnl),
                "fees": float(p.total_fees),
                "funding": float(p.total_funding),
                "net_pnl": float(p.net_pnl),
                "opened_at": p.opened_at.isoformat() if p.opened_at else None,
                "closed_at": p.closed_at.isoformat() if p.closed_at else None,
                "strategy_id": p.strategy_id,
            })
        return journal

    # ──────────────────────────────────────────────
    # Internal
    # ──────────────────────────────────────────────

    def _record_equity(self) -> None:
        self._equity_curve.append({
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "equity": float(self.equity),
            "cash": float(self.cash),
            "unrealized": float(self.unrealized_pnl),
            "realized": float(self.realized_pnl_total),
        })
        # Keep memory bounded
        if len(self._equity_curve) > 50000:
            self._equity_curve = self._equity_curve[-20000:]
