"""
Position tracking with accurate PnL accounting.
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal, ROUND_HALF_UP
from typing import List, Optional, Dict, Any
from uuid import uuid4

from pydantic import BaseModel, Field

from core.types import Side, PositionSide, Fill


class PositionUpdate(BaseModel):
    symbol: str
    side: PositionSide
    quantity_delta: Decimal
    price: Decimal
    fee: Decimal = Decimal("0")
    fee_currency: str = "USDC"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    trade_id: str = ""
    is_funding: bool = False


class ManagedPosition(BaseModel):
    """
    Full-featured position with average entry, realized/unrealized PnL,
    funding, and fee tracking.
    """
    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str
    side: PositionSide = PositionSide.LONG
    quantity: Decimal = Decimal("0")
    entry_price: Decimal = Decimal("0")
    mark_price: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    unrealized_pnl: Decimal = Decimal("0")
    total_fees: Decimal = Decimal("0")
    total_funding: Decimal = Decimal("0")
    leverage: Decimal = Decimal("1")
    margin_type: str = "cross"
    liquidation_price: Optional[Decimal] = None
    strategy_id: str = ""
    opened_at: Optional[datetime] = None
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    closed_at: Optional[datetime] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = {"arbitrary_types_allowed": True}

    @property
    def notional(self) -> Decimal:
        return abs(self.quantity * self.mark_price)

    @property
    def is_open(self) -> bool:
        return self.quantity != 0

    @property
    def net_pnl(self) -> Decimal:
        return self.realized_pnl + self.unrealized_pnl - self.total_fees - self.total_funding

    def apply_fill(self, fill: Fill, is_reduce: bool = False) -> Decimal:
        """
        Apply a fill and return realized PnL generated by this fill.
        Handles average-price accounting correctly for both increasing and reducing.
        """
        qty = fill.quantity
        price = fill.price
        fee = fill.fee
        now = fill.timestamp

        realized = Decimal("0")

        if self.quantity == 0:
            # Opening new position
            self.side = PositionSide.LONG if fill.side == Side.BUY else PositionSide.SHORT
            self.quantity = qty if fill.side == Side.BUY else -qty
            self.entry_price = price
            self.opened_at = now
            self.total_fees += fee
        else:
            current_sign = 1 if self.quantity > 0 else -1
            fill_sign = 1 if fill.side == Side.BUY else -1

            # Same direction → increase
            if current_sign == fill_sign:
                new_qty = abs(self.quantity) + qty
                self.entry_price = (
                    (abs(self.quantity) * self.entry_price + qty * price) / new_qty
                ).quantize(Decimal("0.00000001"), rounding=ROUND_HALF_UP)
                self.quantity = new_qty * current_sign
                self.total_fees += fee
            else:
                # Opposite direction → reduce or reverse
                reduce_qty = min(abs(self.quantity), qty)
                if self.side == PositionSide.LONG:
                    realized = (price - self.entry_price) * reduce_qty
                else:
                    realized = (self.entry_price - price) * reduce_qty

                self.realized_pnl += realized
                self.total_fees += fee

                remaining = abs(self.quantity) - reduce_qty
                if remaining == 0:
                    leftover = qty - reduce_qty
                    if leftover > 0:
                        # Reversed
                        self.side = PositionSide.LONG if fill.side == Side.BUY else PositionSide.SHORT
                        self.quantity = leftover if fill.side == Side.BUY else -leftover
                        self.entry_price = price
                        self.opened_at = now
                    else:
                        self.quantity = Decimal("0")
                        self.closed_at = now
                else:
                    self.quantity = remaining * current_sign

        self.updated_at = now
        self.mark_price = price
        self._recalc_unrealized()
        return realized

    def update_mark(self, mark: Decimal) -> None:
        self.mark_price = mark
        self._recalc_unrealized()
        self.updated_at = datetime.now(timezone.utc)

    def apply_funding(self, funding_payment: Decimal) -> None:
        """Funding is paid/received on open positions (futures)."""
        self.total_funding += funding_payment
        self.updated_at = datetime.now(timezone.utc)

    def _recalc_unrealized(self) -> None:
        if self.quantity == 0:
            self.unrealized_pnl = Decimal("0")
            return
        if self.side == PositionSide.LONG:
            self.unrealized_pnl = (self.mark_price - self.entry_price) * abs(self.quantity)
        else:
            self.unrealized_pnl = (self.entry_price - self.mark_price) * abs(self.quantity)
